### ISSUE TITLE
Quobyte-csi Helm chart fails Helm lint

### ISSUE THREAD

**Issue by Justinsst** [quobyte/quobyte-k8s-resources#3]
Linting the quobyte-csi chart fails with:
```
==> Linting quobyte-csi/
[ERROR] templates/pods/_README.md: file extension '.md' not valid. Valid extensions are .yaml, .yml, .tpl, or .txt
[ERROR] templates/pods/containers/_README.md: file extension '.md' not valid. Valid extensions are .yaml, .yml, .tpl, or .txt
[ERROR] templates/pods/rbac/_README.md: file extension '.md' not valid. Valid extensions are .yaml, .yml, .tpl, or .txt
[ERROR] templates/pods/volumes/_README.md: file extension '.md' not valid. Valid extensions are .yaml, .yml, .tpl, or .txt

Error: 1 chart(s) linted, 1 chart(s) failed

```
This makes the chart uninstallable with Helmfile since you cannot skip the lint step for a specific release. A `.helmignore` file should be included that ignores `.md` file extensions.
```
*.md
```

Versions:
```
helmfile version: v0.158.1
helm version: v3.13.1
```

**Comment by venkatsc** [comment]
Fixed with https://github.com/quobyte/quobyte-csi-driver/pull/95, but this will not be available until the next release.
You can add [.helmignore](https://github.com/quobyte/quobyte-csi-driver/blob/master/csi-driver-templates/.helmignore) to get around the issue.
